name: Apptainer CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Apptainer dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
          build-essential libseccomp-dev pkg-config squashfs-tools cryptsetup curl git

    - name: Install Apptainer
      run: |
        export VERSION=1.2.5
        curl -LO https://github.com/apptainer/apptainer/releases/download/v$VERSION/apptainer-$VERSION.tar.gz
        tar -xzf apptainer-$VERSION.tar.gz
        cd apptainer-$VERSION
        ./mconfig && make -C builddir && sudo make -C builddir install
        cd ..

    - name: Pull MPI-enabled container from DockerHub
      run: |
        apptainer pull mpi_test.sif docker://mpioperator/mpi-base:latest

    - name: Compile your mpi_hello.c
      run: |
        mpicc mpi_hello.c -o mpi_hello

    - name: Run your mpi_hello inside container
      run: |
        apptainer exec mpi_test.sif mpirun -np 2 ./mpi_hello

