name: Apptainer CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Apptainer dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
          build-essential libseccomp-dev pkg-config squashfs-tools cryptsetup runc wget git uuid-dev libgpgme-dev libseccomp-dev libglib2.0-dev

    - name: Install Apptainer
      run: |
        export VERSION=1.2.5
        wget https://github.com/apptainer/apptainer/releases/download/v${VERSION}/apptainer-${VERSION}.tar.gz
        tar -xzf apptainer-${VERSION}.tar.gz
        cd apptainer-${VERSION}
        ./mconfig
        make -C builddir
        sudo make -C builddir install
        cd ..

    - name: Build MPI Hello World container
      run: |
        apptainer build mpi_hello.sif mpi_hello.def

    - name: Run MPI Hello World container
      run: |
        apptainer run mpi_hello.sif

