name: Apptainer CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting CI for Apptainer container"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Apptainer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential libseccomp-dev pkg-config \
            squashfs-tools cryptsetup curl \
            libfuse2 squashfuse fuse2fs

      - name: Install Apptainer
        run: |
          export VERSION=1.2.5
          curl -LO https://github.com/apptainer/apptainer/releases/download/v${VERSION}/apptainer_${VERSION}_amd64.deb
          sudo dpkg -i apptainer_${VERSION}_amd64.deb

      - name: Pull MPI-enabled container from DockerHub
        run: |
          apptainer pull mpi_test.sif docker://ghcr.io/apptainer/mpi-example

      - name: Compile your mpi_hello.c
        run: |
          mpicc -o mpi_hello mpi_hello.c

      - name: Run your mpi_hello inside container
        run: |
          apptainer exec mpi_test.sif mpirun -np 2 ./mpi_hello

